services:
  pyton:
    build: .
    volumes:
        - .:/usr/src/app
    tty: true
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    ports:
      - 8080:8080